version: '3.8'

services:
  # FastAPI Backend (использует Neon DB)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python improved_api_server.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./logs:/app/logs
    restart: unless-stopped

  # Telegram Bot (использует Neon DB)
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file:
      - .env
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./:/app
      - ./logs:/app/logs
    restart: unless-stopped

  # React Frontend (development mode)
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:8080"
    volumes:
      - ./calorie-love-tracker:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped 