name: tvoy_dietolog
description: Твой Диетолог — Android-приложение для трекинга питания
publish_to: 'none'
version: 1.3.2+6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  ota_update: ^6.0.0
  url_launcher: ^6.3.0
  flutter_rustore_update: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
